# Dapr Secrets Store Component - Kubernetes Secrets
# Used for retrieving database credentials and API keys
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets
  namespace: todo-app
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
