# Dapr State Store Component - Redis (Local Development)
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: todo-chatbot
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis-master.todo-chatbot.svc.cluster.local:6379"
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
    - name: ttlInSeconds
      value: "86400"
    - name: keyPrefix
      value: "todo"
