# Dapr Subscription for Notification Service
# US3: Subscribe to reminders topic for notification processing

apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: notification-reminders-sub
spec:
  pubsubname: pubsub
  topic: reminders
  routes:
    default: /api/v1/handle-reminder
  scopes:
    - notification-service
