# Dapr Subscription for Audit Service
# US5: Subscribe to task-events topic for audit logging

apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: audit-task-events-sub
spec:
  pubsubname: pubsub
  topic: task-events
  routes:
    default: /api/v1/handle-event
  scopes:
    - audit-service
