# Dapr Subscription for Recurring Task Service
# US4: Subscribe to task-events topic with routing rules

apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: recurring-task-events-sub
spec:
  pubsubname: pubsub
  topic: task-events
  routes:
    rules:
      - match: event.type == "task.completed"
        path: /api/v1/handle-completed
    default: /api/v1/ignore
  scopes:
    - recurring-task-service
